-- Journal Vido and Searchy bridge downloads only after confirmed delivery.
-- The central migrator owns the transaction; do not add BEGIN/COMMIT here.

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

-- These tables predate the Core migration ledger in production. Defining them
-- here makes a clean Core install capable of exercising the bridge journal
-- contract while remaining a no-op for the existing production tables.
CREATE TABLE IF NOT EXISTS vido.videos (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url_hash                text NOT NULL UNIQUE,
  source_url              text NOT NULL,
  platform                text NOT NULL DEFAULT 'other',
  duration                integer,
  width                   integer,
  height                  integer,
  title                   text,
  author                  text,
  metadata_json           jsonb,
  kind                    text NOT NULL DEFAULT 'video',
  mime_type               text,
  telegram_file_id        text,
  telegram_file_unique_id text,
  file_size               bigint,
  created_at              timestamptz NOT NULL DEFAULT now(),
  last_accessed_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vido.downloads (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      bigint NOT NULL REFERENCES core.person(telegram_user_id),
  video_id     bigint REFERENCES vido.videos(id),
  chat_id      bigint REFERENCES core.chat(chat_id),
  original_url text NOT NULL,
  delivery_key text,
  created_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE vido.downloads
  ADD COLUMN IF NOT EXISTS delivery_key text;

CREATE INDEX IF NOT EXISTS ix_videos_platform
  ON vido.videos (platform);
CREATE INDEX IF NOT EXISTS ix_downloads_user_id
  ON vido.downloads (user_id);
CREATE INDEX IF NOT EXISTS ix_downloads_video_id
  ON vido.downloads (video_id);
CREATE INDEX IF NOT EXISTS ix_downloads_chat_id
  ON vido.downloads (chat_id);
CREATE INDEX IF NOT EXISTS ix_downloads_created_at
  ON vido.downloads (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_vido_downloads_delivery_key
  ON vido.downloads (delivery_key)
  WHERE delivery_key IS NOT NULL;

ALTER TABLE vido.bridge_jobs
  ADD COLUMN IF NOT EXISTS journal_source_key text,
  ADD COLUMN IF NOT EXISTS journal_source_url text;

COMMENT ON COLUMN vido.bridge_jobs.journal_source_key IS
  'Python-normalized SHA-256 key used only for confirmed delivery journaling';
COMMENT ON COLUMN vido.bridge_jobs.journal_source_url IS
  'Python-normalized source URL cleared at terminal delivery state';

-- Exact attribution is impossible while the old producer can still create an
-- unkeyed stats row after mark_ready. Operators must freeze bridge intake and
-- drain every non-terminal job before applying this migration.
CREATE OR REPLACE FUNCTION vido.assert_bridge_journal_rollout_ready()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, vido AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM vido.bridge_jobs
     WHERE status IN (
       'queued', 'processing', 'ready', 'delivering', 'delivery_unknown'
     )
  ) THEN
    RAISE EXCEPTION
      'migration 008 requires a fully drained Vido bridge queue'
      USING ERRCODE = '55000';
  END IF;
END; $$;

SELECT vido.assert_bridge_journal_rollout_ready();

CREATE OR REPLACE FUNCTION vido.clear_terminal_bridge_context()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, vido AS $$
BEGIN
  IF NEW.status = 'ready'
     AND (
       NULLIF(NEW.journal_source_key, '') IS NULL
       OR NULLIF(NEW.journal_source_url, '') IS NULL
     ) THEN
    RAISE EXCEPTION 'ready bridge job requires delivery journal context'
      USING ERRCODE = '23514';
  END IF;
  IF NEW.status = 'failed' THEN
    NEW.source_url := NULL;
    NEW.settings_snapshot := NULL;
    NEW.delivery_plan := NULL;
  END IF;
  IF NEW.status IN ('delivered', 'failed') THEN
    NEW.journal_source_key := NULL;
    NEW.journal_source_url := NULL;
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS clear_terminal_bridge_context
  ON vido.bridge_jobs;
CREATE TRIGGER clear_terminal_bridge_context
BEFORE UPDATE OF status ON vido.bridge_jobs
FOR EACH ROW EXECUTE FUNCTION vido.clear_terminal_bridge_context();

CREATE OR REPLACE FUNCTION vido.clear_existing_failed_bridge_context()
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, vido AS $$
DECLARE
  cleared bigint;
BEGIN
  UPDATE vido.bridge_jobs SET
    source_url = NULL,
    settings_snapshot = NULL,
    delivery_plan = NULL,
    journal_source_key = NULL,
    journal_source_url = NULL
  WHERE status = 'failed'
    AND (
      source_url IS NOT NULL
      OR settings_snapshot IS NOT NULL
      OR delivery_plan IS NOT NULL
      OR journal_source_key IS NOT NULL
      OR journal_source_url IS NOT NULL
    );
  GET DIAGNOSTICS cleared = ROW_COUNT;
  RETURN cleared;
END; $$;

-- Repair payloads retained by the pre-008 invalid_file_id terminal branch.
-- delivery_unknown remains retryable and intentionally keeps context.
SELECT vido.clear_existing_failed_bridge_context();

CREATE OR REPLACE FUNCTION vido.finish_searchy_delivery(
  p_worker_id text,
  p_job_id bigint
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, vido AS $$
DECLARE
  j vido.bridge_jobs%ROWTYPE;
  journal_key text;
  journal_url text;
  journal_platform text;
  journal_video_id bigint;
BEGIN
  SELECT * INTO j FROM vido.bridge_jobs WHERE id = p_job_id FOR UPDATE;
  IF NOT FOUND OR j.target_bot <> 'searchy' THEN
    RETURN false;
  END IF;
  IF j.status = 'delivered' THEN
    RETURN true;
  END IF;
  IF j.status <> 'delivering' OR j.lease_owner IS DISTINCT FROM p_worker_id
     OR j.lease_expires_at IS NULL OR j.lease_expires_at <= now()
     OR jsonb_array_length(COALESCE(j.delivery_plan->'operations', '[]'::jsonb)) = 0
     OR EXISTS (
       SELECT 1 FROM jsonb_array_elements(j.delivery_plan->'operations') item
        WHERE NOT EXISTS (
          SELECT 1 FROM vido.delivery_operations o
           WHERE o.job_id = p_job_id
             AND o.operation_id = item->>'operation_id'
             AND o.status = 'delivered'
        )
     ) THEN
    RETURN false;
  END IF;

  journal_url := NULLIF(j.journal_source_url, '');
  journal_key := NULLIF(j.journal_source_key, '');
  IF journal_url IS NULL OR journal_key IS NULL THEN
    RAISE EXCEPTION 'bridge job % has no delivery journal context', p_job_id;
  END IF;

  journal_platform := CASE
    WHEN j.platform IS NULL OR j.platform IN ('', 'unknown') THEN 'other'
    ELSE j.platform
  END;

  INSERT INTO vido.videos AS existing (url_hash, source_url, platform)
  VALUES (journal_key, journal_url, journal_platform)
  ON CONFLICT (url_hash) DO UPDATE SET
    last_accessed_at = now(),
    platform = CASE
      WHEN existing.platform IN ('other', 'unknown')
       AND EXCLUDED.platform <> 'other' THEN EXCLUDED.platform
      ELSE existing.platform
    END
  RETURNING id INTO journal_video_id;

  INSERT INTO vido.downloads(
    user_id, video_id, chat_id, original_url, delivery_key
  ) VALUES (
    j.owner_user_id, journal_video_id, j.target_chat_id, j.source_url,
    'bridge:' || p_job_id::text
  )
  ON CONFLICT (delivery_key) WHERE delivery_key IS NOT NULL DO NOTHING;

  UPDATE vido.bridge_jobs SET
    status = 'delivered', delivered_at = now(), updated_at = now(),
    source_url = NULL, settings_snapshot = NULL, delivery_plan = NULL,
    journal_source_key = NULL, journal_source_url = NULL,
    lease_owner = NULL, lease_expires_at = NULL
  WHERE id = p_job_id;
  UPDATE vido.artifact_leases SET released_at = now()
   WHERE job_id = p_job_id AND released_at IS NULL;
  PERFORM pg_notify('vido_bridge', p_job_id::text || ':delivered');
  PERFORM pg_notify('vido_artifact_release', p_job_id::text);
  RETURN true;
END; $$;

REVOKE ALL ON FUNCTION vido.clear_terminal_bridge_context()
  FROM PUBLIC;
REVOKE ALL ON FUNCTION vido.clear_existing_failed_bridge_context()
  FROM PUBLIC;
REVOKE ALL ON FUNCTION vido.assert_bridge_journal_rollout_ready()
  FROM PUBLIC;
REVOKE ALL ON FUNCTION vido.finish_searchy_delivery(text,bigint)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION vido.finish_searchy_delivery(text,bigint)
  TO searchy_core;

GRANT SELECT, INSERT, UPDATE, DELETE ON vido.videos, vido.downloads
  TO vido_core;
GRANT USAGE, SELECT ON SEQUENCE vido.videos_id_seq, vido.downloads_id_seq
  TO vido_core;

-- Keep clean-install ownership aligned with the existing production schema.
ALTER TABLE vido.videos OWNER TO vido_core;
ALTER TABLE vido.downloads OWNER TO vido_core;
ALTER SEQUENCE vido.videos_id_seq OWNER TO vido_core;
ALTER SEQUENCE vido.downloads_id_seq OWNER TO vido_core;
